version: 2

sources:
  - name: raw_2014_reddit_comments
    description: The full BigQuery results for archived 2014 reddit comments
    tables:
      - name: full_comments_2014
        columns:
          - name: id
            description: comment id, primary key
            tests:
              - unique
              - not_null
          - name: author
            description: author's username
            tests:
              - not_null
          - name: subreddit
            description: subreddit posted upon
            tests:
            - not_null
          - name: score
            description: comment score
            tests:
            - not_null
          - name: created_utc
            description: time comment was created as UTC timestamp
            tests:
            - not_null
          - name: body
            description: body text of comment
            tests:
            - not_null

models:
  - name: stg_2014_comments__funny
    description: Viewing 2014 comments from the 'funny' subreddit
    columns:
          - name: comment_id
            description: comment id, primary key
            tests:
              - unique
              - not_null
          - name: author
            description: author's username
            tests:
              - not_null
          - name: subreddit
            description: subreddit posted upon
            tests:
            - not_null
                config:
                  where: "subreddit = funny"
          - name: score
            description: comment score
            tests:
            - not_null
          - name: hour
            description: hour comment was created from UTC timestamp
            tests:
            - not_null
            meta:
              dbt_utils.type: dbt_utils.datetime.datetime
          - name: day
            description: day comment was created from UTC timestamp
            tests:
            - not_null
            meta:
              dbt_utils.type: dbt_utils.datetime.datetime
          - name: month
            description: month comment was created from UTC timestamp
            tests:
            - not_null
            meta:
              dbt_utils.type: dbt_utils.datetime.datetime              
          - name: year
            description: year comment was created from UTC timestamp
            tests:
            - not_null
                config:
                  where: "year = 2014"
            meta:
              dbt_utils.type: dbt_utils.datetime.datetime 
          - name: body
            description: body text of comment
            tests:
            - not_null